from .shapeZ08KatayamaLib import *
from .version import *   # generated by sconsUtils unless you tell it not to

from lsst.meas.algorithms import AlgorithmRegistry

AlgorithmRegistry.register("shape.z08", ShapeZ08KatayamaControl)
